apiVersion: v1
kind: Secret
metadata:
  name: rds-secret
type: Opaque
data:
  db_host: dGVzdGRiMDAxLmNhcnVwaGp4dXlpai5hcC1ub3J0aGVhc3QtMi5yZHMuYW1hem9uYXdzLmNvbQ==
  db_user: dXNlcm5hbWU=
  db_password: cGFzc3dvcmQ=
